Led support
Laikata/Software pull request #7
Opened 2022-05-14 16:19 UTC by Tiliy6

Added led display to show battery status, indicating a color respectively to its voltage and current. It also blinks to save energy, instead of having it on all the time.

2022-05-14 16:31 UTC, salmonmolon commented on lib/leds/src/leds.h
> +void updateLeds();
Newline is missing
```suggestion
void updateLeds();

```

2022-05-14 16:42 UTC, salmonmolon requested changes

2022-05-14 16:42 UTC, salmonmolon commented on lib/leds/src/leds.cpp
> +}
Newline is missing
```suggestion
}

```

2022-05-14 16:42 UTC, salmonmolon commented on lib/leds/src/leds.h
> +void updateLeds();
Newline is missing
```suggestion
void updateLeds();

```

2022-05-14 16:42 UTC, salmonmolon commented on lib/leds/src/leds.cpp
> +        else if (valor <= 3.6) {
Change to english
```suggestion
    float value = analogRead(A0);
    value = value*4.7f/1023;

    static unsigned long tNextLed = millis();
    static unsigned long tNextOff;

    if (millis() > tNextLed) {
        tNextLed = millis() + 2000;
        if (valor >= 3.8) {
            leds[0] = CRGB::Green;
        }
        else if (value <= 3.6) {
```

2022-05-14 16:50 UTC, salmonmolon approved these changes
Looks ok to me

2022-05-20 22:17 UTC, Arnau478 commented
I think this was done outside of the PR, on main branch.
Closing!

2022-05-20 22:17 UTC, closed without merging